"""
Lista estática de domínios de e-mail descartáveis (disposable / temporary).

Usada para bloquear pedidos do fluxo freemium feitos com e-mails throwaway,
que são vetor clássico de abuso (mesmo usuário tentando burlar a blacklist
com e-mails diferentes).

Snapshot inspirado em listas open-source (e.g. `disposable-email-domains` no GitHub).
Mantemos como lista estática para evitar dependência runtime e dar controle
explícito sobre o que rejeitamos.

Domínios devem estar em lowercase. A função `is_disposable` em
`clama.freemium.services.email_blacklist` faz a normalização do input.
"""

DISPOSABLE_EMAIL_DOMAINS: frozenset[str] = frozenset({
    # 10minutemail e variantes
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.org",
    "10minemail.com",
    "10minutesmail.com",
    "20minutemail.com",
    "30minutemail.com",
    # mailinator e variantes
    "mailinator.com",
    "mailinator.net",
    "mailinator.org",
    "mailinator2.com",
    "mailinater.com",
    "mailinator.us",
    "reallymymail.com",
    # guerrillamail e variantes
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamail.biz",
    "guerrillamail.de",
    "guerrillamailblock.com",
    "sharklasers.com",
    "grr.la",
    "spam4.me",
    # tempmail e variantes
    "tempmail.com",
    "temp-mail.com",
    "temp-mail.org",
    "tempmail.net",
    "tempmail.us",
    "tempmail.de",
    "tempmail.email",
    "tempmailer.com",
    "tempmailo.com",
    "tempinbox.com",
    "tmpmail.org",
    "tmpmail.net",
    # throwaway / yopmail
    "throwawaymail.com",
    "throwawayemailaddresses.com",
    "yopmail.com",
    "yopmail.net",
    "yopmail.fr",
    "cool.fr.nf",
    "jetable.fr.nf",
    "nospam.ze.tc",
    "nomail.xl.cx",
    "mega.zik.dj",
    "speed.1s.fr",
    "courriel.fr.nf",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "monmail.fr.nf",
    # outros providers descartáveis comuns
    "fakemail.net",
    "fakeinbox.com",
    "fakemailgenerator.com",
    "getnada.com",
    "nada.email",
    "trashmail.com",
    "trashmail.net",
    "trashmail.de",
    "trashmail.io",
    "trashmail.ws",
    "wegwerfmail.de",
    "dispostable.com",
    "discard.email",
    "discardmail.com",
    "discardmail.de",
    "spambox.us",
    "spambog.com",
    "mintemail.com",
    "mytemp.email",
    "maildrop.cc",
    "mailnesia.com",
    "mailcatch.com",
    "mailnull.com",
    "mailmoat.com",
    "moakt.com",
    "owlymail.com",
    "tutye.com",
    "emailondeck.com",
    "mohmal.com",
    "inboxalias.com",
    "inboxbear.com",
    "instant-mail.de",
    "vomoto.com",
    "mailtothis.com",
    "fast-mail.fr",
    "1secmail.com",
    "1secmail.net",
    "1secmail.org",
    "harakirimail.com",
    "linshiyouxiang.net",
    "rtrtr.com",
    # outros nomes diversos
    "byom.de",
    "deadaddress.com",
    "emailmiser.com",
    "tempr.email",
    "fakeemail.de",
    "tempemail.com",
    "tempemail.net",
    "toastmail.io",
    "mailtemp.info",
    "nowmymail.com",
    "anonbox.net",
    "anonymail.dk",
    "onetimeuse.com",
    "pokemail.net",
    "mvrht.com",
    "trash-mail.at",
    "trash-mail.com",
    "trash-mail.de",
    "easytrashmail.com",
    "incognitomail.com",
    "tempemailaddress.com",
    "shitmail.me",
    "spamgourmet.com",
    "spamgourmet.net",
    "spamgourmet.org",
    "spambooger.com",
    "yepmail.net",
    "kasmail.com",
    "objectmail.com",
    "binkmail.com",
})
