# Generated by Django 4.2.30 on 2026-05-13 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_html', models.TextField()),
                ('conteudo_tiptap_json', models.JSONField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('imagem_capa_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('historia_ilustrativa', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_autorados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-data_publicacao', '-created_at'],
                'indexes': [models.Index(fields=['status', '-data_publicacao'], name='idx_blog_post_status_pub'), models.Index(fields=['slug'], name='idx_blog_post_slug')],
            },
        ),
    ]
