# Generated by Django 4.2.30 on 2026-05-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial_blog_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField(max_length=2000)),
                ('ip_address', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('is_suspeito', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_blog', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('like', 'Like')], default='like', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_blog', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='blog.post')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'tipo'], name='idx_blog_reacao_post_tipo')],
            },
        ),
        migrations.AddConstraint(
            model_name='reacao',
            constraint=models.UniqueConstraint(fields=('post', 'customer', 'tipo'), name='uniq_blog_reacao_post_customer_tipo'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['post', '-created_at'], name='idx_blog_comentario_post_crtd'),
        ),
    ]
