# Generated by Django 4.2.30 on 2026-05-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_add_comentario_reacao_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBanido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('banido_em', models.DateTimeField(auto_now_add=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('banido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banimentos_aplicados', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banimentos', to=settings.AUTH_USER_MODEL)),
                ('revogado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banimentos_revogados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer banido',
                'verbose_name_plural': 'Customers banidos',
                'ordering': ['-banido_em'],
                'indexes': [models.Index(fields=['customer', 'revogado_em'], name='idx_blog_banido_cust_revog')],
            },
        ),
    ]
