# Generated by Django 4.2.30 on 2026-08-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comentario_e_reacao_ancoram_no_espelho"),
    ]

    operations = [
        migrations.AddField(
            model_name="postespelho",
            name="post_legado",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="espelho",
                to="blog.post",
            ),
        ),
    ]
