volumes:
  clama_backend_local_postgres_data: {}
  clama_backend_local_redis_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: clama_backend_local_django
    container_name: clama_backend_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:16
    container_name: clama_backend_local_postgres
    volumes:
      - clama_backend_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-clama_backend}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: clama_backend_local_redis
    volumes:
      - clama_backend_local_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: clama_backend_local_celeryworker
    container_name: clama_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start-celeryworker

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: clama_backend_local_celerybeat
    container_name: clama_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start-celerybeat

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: clama_backend_local_flower
    container_name: clama_backend_local_flower
    depends_on:
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5555:5555"
    command: /start-flower
