version: "3.9"

volumes:
  production_postgres_data: {}
  production_redis_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: clama_backend_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: postgres:16
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:7
    volumes:
      - production_redis_data:/data

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: clama_backend_production_celeryworker
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start-celeryworker

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: clama_backend_production_celerybeat
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start-celerybeat
