# Generated by Django 4.2.30 on 2026-04-10 02:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('versao', models.PositiveIntegerField(verbose_name='Versão')),
                ('system_prompt', models.TextField(help_text='Prompt do sistema enviado ao Claude definindo a identidade do Clama.', verbose_name='System prompt')),
                ('instrucoes_por_complexidade', models.JSONField(default=dict, help_text='Dict mapeando complexidade do plano para instrução adicional.', verbose_name='Instruções por complexidade')),
                ('ativo', models.BooleanField(default=False, help_text='Apenas um template pode estar ativo por vez.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompt',
                'ordering': ['-versao'],
            },
        ),
    ]
