# Generated by Django 4.2.30 on 2026-04-10 02:12

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_seed_planos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Nome')),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(verbose_name='E-mail')),
                ('telefone', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='Telefone')),
                ('idade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('sexo', models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao_informado', 'Não informado')], default='', max_length=20, verbose_name='Sexo')),
                ('pedido_oracao', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Pedido de oração')),
                ('oracao_gerada', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='Oração gerada')),
                ('valor_centavos', models.IntegerField(verbose_name='Valor (centavos)')),
                ('canal_entrega', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Canal de entrega')),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('gerando_oracao', 'Gerando oração'), ('oracao_gerada', 'Oração gerada'), ('enviada', 'Enviada'), ('erro', 'Erro')], default='aguardando_pagamento', max_length=40, verbose_name='Status')),
                ('asaas_charge_id', models.CharField(blank=True, default='', max_length=80, verbose_name='ID da cobrança Asaas')),
                ('asaas_invoice_url', models.URLField(blank=True, default='', verbose_name='URL do checkout Asaas')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
