# Generated by Django 4.2.30 on 2026-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='consent_aceito',
            field=models.BooleanField(default=False, verbose_name='Consentimento aceito'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='consent_aceito_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do consentimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do consentimento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='consent_versao',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Versão da política aceita'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Último erro registrado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Contagem de retentativas'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='whatsapp_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega WhatsApp'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ID da mensagem WhatsApp'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='whatsapp_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de leitura WhatsApp'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('gerando_oracao', 'Gerando oração'), ('oracao_gerada', 'Oração gerada'), ('enviada', 'Enviada'), ('aguardando_reenvio', 'Aguardando reenvio'), ('erro', 'Erro')], default='aguardando_pagamento', max_length=40, verbose_name='Status'),
        ),
    ]
