# Generated by Django 4.2.30 on 2026-04-11 18:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_consent_aceito_pedido_consent_aceito_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cpf_cnpj',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', verbose_name='CPF/CNPJ'),
        ),
    ]
