# Generated by Django 4.2.30 on 2026-07-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_asaas_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pix_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='Pix copia-e-cola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Pix QR code (PNG base64)'),
        ),
    ]
