# Generated by Django 4.2.30 on 2026-04-16 12:09

import clama.documents.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContexto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome identificador do documento', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do conteúdo e propósito do documento')),
                ('arquivo', models.FileField(help_text='Arquivo PDF ou texto plano (máx 100MB)', upload_to=clama.documents.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])])),
                ('tipo_mime', models.CharField(help_text='Tipo MIME do arquivo (application/pdf ou text/plain)', max_length=50)),
                ('tamanho_bytes', models.PositiveIntegerField(help_text='Tamanho do arquivo em bytes')),
                ('anthropic_file_id', models.CharField(blank=True, help_text='ID do arquivo na Files API da Anthropic', max_length=100, null=True)),
                ('data_sincronizacao', models.DateTimeField(blank=True, help_text='Data/hora da última sincronização com Anthropic', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se ativo, será incluído no contexto das orações')),
            ],
            options={
                'verbose_name': 'Documento de Contexto',
                'verbose_name_plural': 'Documentos de Contexto',
                'ordering': ['-created_at'],
            },
        ),
    ]
