# Generated by Django 4.2.30 on 2026-04-16 13:13

import clama.documents.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocontexto',
            name='arquivo',
            field=models.FileField(help_text='Arquivo PDF, DOCX ou texto plano (máx 100MB)', upload_to=clama.documents.models.documento_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='documentocontexto',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Se ativo, será incluído no contexto das orações. Ativar sincroniza automaticamente.'),
        ),
        migrations.AlterField(
            model_name='documentocontexto',
            name='tipo_mime',
            field=models.CharField(help_text='Tipo MIME do arquivo', max_length=100),
        ),
    ]
