# Generated by Django 4.2.30 on 2026-04-10 02:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('valor_centavos', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000, message='Valor mínimo é R$ 20,00')])),
                ('descricao', models.TextField()),
                ('complexidade', models.CharField(choices=[('simples', 'Simples'), ('com_versiculo', 'Com versículo'), ('com_profecia_e_versiculos', 'Com profecia e versículos')], default='simples', max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ('ordem',),
            },
        ),
    ]
