# Generated by Django 4.2.30 on 2026-04-18 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_seed_planos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='valor_centavos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Valor mínimo é R$ 0,01')]),
        ),
    ]
