# Generated by Django 4.2.30 on 2026-04-10 11:23

import clama_backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', clama_backend.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_clama_admin',
            field=models.BooleanField(default=False, help_text='Designa se o usuário pode acessar o painel admin do Clama.', verbose_name='Admin do Clama'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
