# Generated by Django 4.2.30 on 2026-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_email_hash_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_format_blog',
            field=models.CharField(choices=[('completo', 'Nome completo (Juliana Silva)'), ('compacto', 'Primeiro nome + inicial (Juliana S.)')], default='compacto', max_length=20, verbose_name='Formato do nome no blog'),
        ),
    ]
