# Generated by Django 4.2.30 on 2026-05-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_nome_format_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade (pré-preenchimento)'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao_informado', 'Não informado')], default='', max_length=20, verbose_name='Sexo (pré-preenchimento)'),
        ),
    ]
