# Generated by Django 4.2.30 on 2026-04-10 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_pedido_consent_aceito_pedido_consent_aceito_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('ASAAS', 'Asaas'), ('ZAPI', 'Z-API')], help_text='Provedor de origem do webhook', max_length=20)),
                ('external_event_id', models.CharField(help_text='ID único do evento no provedor', max_length=120)),
                ('event_type', models.CharField(help_text='Tipo do evento (ex: PAYMENT_CONFIRMED)', max_length=80)),
                ('payload', models.JSONField(help_text='Payload completo do webhook')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSADO', 'Processado'), ('IGNORADO', 'Ignorado'), ('ERRO', 'Erro')], default='RECEBIDO', help_text='Status de processamento', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Mensagem de erro (quando status=ERRO)')),
                ('pedido', models.ForeignKey(blank=True, help_text='Pedido associado (se identificável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='payments_we_provide_966485_idx'), models.Index(fields=['created_at'], name='payments_we_created_d9f30c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevento',
            constraint=models.UniqueConstraint(fields=('provider', 'external_event_id'), name='uq_webhook_event_provider_id'),
        ),
    ]
